name: Run Tests
on: push
jobs:
  test:
    name: Run Test suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: dockerfile.ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker images
        run: |
          docker buildx build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache,mode=max \
            --tag main:latest \ # Ensure the image is tagged as main:latest
            -f $COMPOSE_FILE \
            .

      - name: Start Storybook
        run: |
          npm run storybook &
          sleep 20 # Adjust the sleep time as needed to ensure Storybook is fully started

      - name: Run tests
        run: docker run main:latest # Use the correct tag
        continue-on-error: false