name: Run Tests

on: push

jobs:
  test:
    name: Run Test suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker images
        run: docker build -t main -f Dockerfile.ci .

      - name: Run tests
        run: docker run main
